version: '3.8'

services:
  dind:
    image: docker:19.03.12-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    networks:
      - app-network

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://walab.handong.edu:3306/p231_21900766?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: p231_21900766
      SPRING_DATASOURCE_PASSWORD: kioG7u
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    depends_on:
      - dind
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - springboot
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


#    EMsORysrjxLwTHUE