version: "3.8"

services:
  dind:
    image: docker:19.03.12-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - /tmp:/tmp
    networks:
      - app-network

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://walab.handong.edu:3306/hissolve?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: hissolve
      SPRING_DATASOURCE_PASSWORD: EMsORysrjxLwTHUE
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    ports:
      - "9090:9090"
    depends_on:
      - dind
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
